monach/base/urls.py
from django.urls import path
from .views import home_view

app_name = "base"

urlpatterns = [
    path('', home_view, name="home")
]

monach/monach/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('accounts.urls'))
]

monach/templates/snippets/footer.html
<style type="text/css">
    .ffd {
        padding: 1em;
        min-height: 100px;
    }
    
    #footer {
        bottom: 0;
        width: 100%;
    }
</style>
<div class="ffd" id="footer">
    <footer class="border-top">
        <div class="row">
            <div class="col-6 col-md">
                <h5>Contact Us</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="#">Contact</a>
                    </li>
                    <li><a class="text-muted" href="#">Stuff for developers</a></li>
                    <li><a class="text-muted" href="#">Another one</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Follow us</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Facebook</a></li>
                    <li><a class="text-muted" href="#">Instagram</a></li>
                    <li><a class="text-muted" href="#">Linked In</a></li>
                    <li><a class="text-muted" href="#">Youtube</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>About Us</h5>
                <ul class="list-unstyled text-small">
                    <li>
                        <a class="text-muted" href="#">Locations</a>
                    </li>
                    <li><a class="text-muted" href="#">Privacy</a></li>
                    <li>
                        <a class="text-muted" href="#">Terms & conditions</a
              >
            </li>
          </ul>
        </div>
      </div>
      <div>
        
        <h3 style="text-align: center;">Monarch Coding School</h3>
        <h3 style="text-align: center; color: green">&copy; 2020</h3>
        <p></p>
      </div>
    </footer>
  </div>

monach/templates/snippets/nav.html
<style>
    .search-bar {
        max-width: 500px;
        width: 100%;
    }
    
    form {
        width: 100%;
    }
</style>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">
        <a class="my-2 my-md-0 mr-md-3" href="{% url 'base:home' %}">Monarch Coding School</a> {% if request.user.is_authenticated %}
        <p>Hello, {{request.user.username}}</p>
        {% endif %}
    </h5>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if request.user.is_authenticated %}
        <a class="p-2 text-dark" href="#" style="padding-right: 8px">Home</a
      >
      <a
        class="p-2 text-dark"
        href="#"
        style="padding-right: 8px"
        >Account</a
      >
      <a
        class="p-2 text-dark"
        href="#"
        style="padding-right: 8px"
        >Logout</a
      >
      {% else %}
      <a class="p-2 text-dark" href="#" style="padding-right: 8px"
        >Home</a
      >
      <a class="p-2 text-dark" href="{% url 'login' %}" style="padding-right: 8px"
        >Login</a
      >
      <a
        class="p-2 text-dark"
        href="#"
        style="padding-right: 8px"
        >Register</a
      >
      {% endif %}
    </nav>
  </div>